### ISSUE TITLE
No attribute 'next'

### ISSUE THREAD

**Issue by menardmc** [ThaWeatherman/scrapers#5]
When running extract_ids.py I'm getting the following error:

Traceback (most recent call last):
  File "extract_ids.py", line 6, in <module>
    col = reader.next().index('id')
AttributeError: '_csv.reader' object has no attribute 'next'

Destination txt file is being populated with IDs, but not the complete list.

**Comment by howdydoody123** [comment]
That scraper was written in Python 2, not 3.
